spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: Market
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true

stripe:
  api:
    key: sk_main_PetMarket

flyway:
  baseline-on-migrate: true
  debug: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

